### ISSUE TITLE
Error while running code

### ISSUE THREAD

**Issue by deepanshuparuthi** [Karan-Malik/FaceMaskDetector#8]
![Screenshot 2021-04-26 161550](https://user-images.githubusercontent.com/83217147/116070835-b407e700-a6aa-11eb-8006-c83030c65384.png)

**Comment by Karan-Malik** [comment]
This is not a problem with the code, but with the Keras installation on your system. You can resolve it by reinstalling the Keras library from your command prompt. 

If this does not solve your problem, you can try downgrading tensorflow by using the following command:
```
pip install tensorflow==2.1.0
```

**Comment by deepanshuparuthi** [comment]
Can you please tell me that on which version of python the code was written?  I'm getting this error now after trying a lot. 
help me with this... 
or please tell me step by step which version of python I have to use then which are the libraries I have to install.
I have followed all the instructions from the readme file in the project, still, I'm not able to run that.
![Screenshot 2021-04-27 114727](https://user-images.githubusercontent.com/83217147/116219086-d95b2a80-a768-11eb-8fb7-27d28ce266fa.png)
