### ISSUE TITLE
Can you please tell me that on which version of python the code was written?  I'm getting this error now after trying a lot.

### ISSUE THREAD

**Issue by deepanshuparuthi** [Karan-Malik/FaceMaskDetector#9]
Can you please tell me that on which version of python the code was written?  I'm getting this error now after trying a lot. 
help me with this... 
or please tell me step by step which version of python I have to use then which are the libraries I have to install.
I have followed all the instructions from the readme file in the project, still, I'm not able to run that.
![Screenshot 2021-04-27 114727](https://user-images.githubusercontent.com/83217147/116219086-d95b2a80-a768-11eb-8fb7-27d28ce266fa.png)

_Originally posted by @deepanshuparuthi in https://github.com/Karan-Malik/FaceMaskDetector/issues/8#issuecomment-827462755_

**Comment by Karan-Malik** [comment]
The code was written on Python 3.7.

For the library versions used you can check the requirements.txt file in the repository.

**Comment by deepanshuparuthi** [comment]
i got this now 
![Screenshot 2021-04-27 153350](https://user-images.githubusercontent.com/83217147/116224206-fe05d100-a76d-11eb-8cf5-48a23aba64fd.png)

**Comment by Karan-Malik** [comment]
You haven't included the error in this image. Send the image of the last few lines of the error you receive.

**Comment by deepanshuparuthi** [comment]
Here it is
![Screenshot 2021-04-27 163021](https://user-images.githubusercontent.com/83217147/116231009-f6e2c100-a775-11eb-8fc0-f1691ebef71a.png)

**Comment by deepanshuparuthi** [comment]
that error was solved using pillow library..help me solve this one
![Screenshot 2021-04-27 165536](https://user-images.githubusercontent.com/83217147/116233816-6ad29880-a779-11eb-9c78-e3bd9dcd1261.png)

**Comment by deepanshuparuthi** [comment]
Resolved all the errors, Thanks!

**Comment by utsapkota** [comment]
> Resolved all the errors, Thanks!

How was this issue resolved?
